# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
os:  linux

env:
  global:
    # TODO Update this to match the name of your project.
    - CRATE_NAME=rust-tuya-mqtt

jobs:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:

    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: beta
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl
      rust: stable
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust: stable

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  token:
    secure: Lyz4ZHtS1nyL9FjRA2CnwxY4ndyE9j612ej+XjImRH44l8kymxNjbUeNR7MZKQP8rgOzZ3x44z1AOIBbUqmErfNs8Q0pwHjr+D6JvXfNNQIX4Yd9dmx1QwMelfUZ24/imc8gmQQUAcVZXDDR1Lp2E/xPcfi8aUiBE/TivKiLRBTtJeGtsYRevCiF973r1/9iE7k5FvAHNDmrM7zgDbc42EWMb1fJ24GqTMbhxAYwgzWoNxjGb6JqwhkG3cOaLuJMCzVDVOA92liJhCGS0724pqpQPRqJNK0rQJiaGiCBdel7Nq8XhG0FAaGZONN8BD5FyoxkznFkzIWgzQEOPg8skim5Ch/7nPRwxBHTLi7rEzZOIeY0PrsKqD+zwJOFhXAwx26p+zo+ejARTat+td9RlU5iqas32ZdghWycYXy9jDafR4dQsT+0hXeMDRcxn/gxreGV7mN5ylgKRKX623Cschs1SDnSmQs7iw2aAgAyanfwGMWGi5EguhIx0CBCNZxHR2MGntuTtkVUJt2S+PU0EcDQ8DHNoYloGxxHwQNNXgK7wGlnU85C843HXJb6qr082RQXrJhDSflplIo6TxYmqdLDL3mmULXTheSLJKPCIT/2tMIw2EowbSEZF4RhMhX3xFSotykSKKXu/lxxlcv6FIK+Imr/wNZwCwSCFxIEZps=
  file_glob: true
  file: '$CRATE_NAME-$TRAVIS_TAG-$TARGET.*'
  on:
    # TODO Here you can pick which targets will generate binary releases
    # In this example, there are some targets that are tested using the stable
    # and nightly channels. This condition makes sure there is only one release
    # for such targets and that's generated using the stable channel
    condition: $TRAVIS_RUST_VERSION = stable
    repo: EmilSodergren/rust-tuya-mqtt
    tags: true
  cleanup: false
  edge: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
