[package]
name = "rust-tuya-mqtt"
version = "0.1.0"
authors = ["Emil Sodergren <EmilSodergren@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.3"
ctrlc = { version = "3.1", features = ["termination"] }
env_logger = "0.7"
failure = "0.1"
log = "0.4"
rumqtt = "0.31"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
rust-tuyapi = { path = "../rust-tuyapi"}
pretty_env_logger = "0.4"
